### ISSUE TITLE
Use environment in commands

### ISSUE THREAD

**Issue by syphernl** [valorin/deploy#1]
Would it be possible to pass the specific "deploying to" environment to the commands?

For instance, If I need to deploy to "acceptance" it should issue:

```
env APPLICATION_ENV=development php artisan migrate --force
```

And for production:

```
env APPLICATION_ENV=production php artisan migrate --force
```

(This is due to different DB configs for different environments)

Perhaps a "parameter" could be added like:

```
    'commands' => array(
        'php artisan down',
        'git pull',
        'composer install --no-dev',
        'env APPLICATION_ENV={name} php artisan migrate --force',
        'php artisan up',
    ),
```

which gets replaced by the deploy script?

which gets replaced with the parameter given on the command line

**Comment by valorin** [comment]
That's a really good idea, will definitely have a think about a good way to do it. :-)

I currently use `.env.php` files (http://laravel.com/docs/configuration#protecting-sensitive-configuration) to manage site specific config. Might be a good workaround?

**Comment by syphernl** [comment]
I generally use `app/config/environment/app.php` (etc) for environment specific settings (including the app key) but this approach does not work with "packages" (or I haven't figured out how). 

The `.env.local.php` could be an option, but that would also make it a reference-mess where the config refers to something that originated somewhere else :) I also do not like that much stuff to be crammed into the `$_ENV` superglobal either. Might still be a good workaround for this particular issue though.

**Comment by valorin** [comment]
Yeah, I agree that reference-mess is never fun. Although, for database credentials (for example), keeping them out of git keeps them a bit more secure, and since they are unique per host - it removes confusion across sites.

All of that said, would something like this work?

```
./artisan deploy --option="env=development" --option="key=value"
```

So deploy accepts multiple `--option` flags which are in the format: `key=value`.
The system will then replace all instances of `{key}` with `value` before running each command, and do this for each provided option on each command. So you should be able to set the command templates and customise them as much as needed.

The only issue would be handling default values. The options are:
1. Do nothing and require the option to be provided or the command will likely fail when run.
2. Look for tokens in the form `{key|default}`, and apply the default if no option provided.
3. Try and use Blade to render each command, to support things like {{ $this or 'that' }}

#1 is sloppy, and #3 is overly complicated, so #2 is the best option. I'll probably run with that.

Does this sound like it will work?

**Comment by syphernl** [comment]
Sounds good to me. Perhaps it could be even easier though:

```
./artisan deploy --set-env="development" --set-key="value"
```

Its probably also a good idea to throw an error when there is an unreplaced parameter (not provided on commandline, no default value available).

**Comment by valorin** [comment]
I thought of that, but without diving deep into Symfony Console, it's not possible to handle user specified command options. It might not even be possible given the way Laravel implements artisan commands. 

Taylor cheated for Envoy and uses the Symfony console directly, to support it's option setting...

**Comment by valorin** [comment]
Would need to override a function in https://github.com/laravel/framework/blob/4.2/src/Illuminate/Console/Command.php, to add in the provided options so they can be registered. 

Will see how simple it is.

Good point about throwing an error for a missing option.

**Comment by valorin** [comment]
Ok, take a look at the commit I just pushed. It implements option tags in the form:

```
    'commands' => array(
        'down'     => 'php artisan down:safe',
        'checkout' => 'git checkout -f {branch|master}',
        'fetch'    => 'git fetch {remote|origin}',
        'tags'     => 'git fetch {remote|origin} --tags',
        'pull'     => 'git pull -f {remote|origin} {branch|master}',
        'composer' => 'composer install {composer-args|--no-dev}',
        'up'       => 'php artisan up',
```

With the command looking something like this:

```
./artisan deploy --set-composer-args="--no-scripts" --set-remote="github"
```

It should allow you to easily customise your environment, and set a default value when you don't provide one. It should also block commands and throw an error if a tag is not provided and there is no default value.

I also updated the default commands to the list above - so you can use `branch`, `remote`, and `composer-args` out of the box, and keys to update existing commands without needing to replace the entire list.

Have a go and see if it works for you, and if so, I'll tag it as the next version :-)

**Comment by valorin** [comment]
This seems to work in my testing, so I'll close this and tag `v1.2`.

Let me know if you have any problems with it :-)
